### ISSUE TITLE
Please check the operation of CMS in Cyrillic.

### ISSUE THREAD

**Issue by aukc1970** [pagecarton/pagecarton#6]
Good day! Please check the operation of CMS in Cyrillic.
Can't create a page in Russian in Cyrillic shows an error. Then create the English page is created but then have to rename Russian to Cyrillic.
Instead of Russian words in Cyrillic in the code displays this `&#1043;&#1083;&#1072;&#1074;&#1085;&#1072;&#1103;`

**Comment by ayoolafalola** [comment]
Okay. Working on this and will release a patch soon.

**Comment by aukc1970** [comment]
Thank you ! I'll wait !

**Comment by ayoolafalola** [comment]
Kindly confirm this issue has been fixed by transliterating cyrillic and similar characters in page, post and profile URLs.

Upgrade your PageCarton installation to version 1.6.68

**Comment by aukc1970** [comment]
Thank you ! Good ! I'll try !

**Comment by aukc1970** [comment]
Thanks for the quick fix! Now creating a page in Russian on Cyrillic works! The error remained in the menu when you rename the English item to Russian, then the test turns out to be encoded. Links to screenshots before and after application.
https://drive.google.com/open?id=1mf5NNmb2w6ORZu9Z35ZBiDnITjg_jYW1
https://drive.google.com/open?id=11qqRUg-_Cbm6-WaPOzts7r5-vPDJ04Ko
https://cloud.mail.ru/public/4VUo/dPEVAyXCF
https://cloud.mail.ru/public/5Dht/4K6S3SbWd

**Comment by aukc1970** [comment]
I tried with another template. The page creates well without errors. But in the code text is encoded. Here are the screenshots.
https://drive.google.com/open?id=1DSS6k884uG9PPEhTfSE5OhxrIeSQ6BXH 
https://drive.google.com/open?id=1f0hK-txzxhc_Ggp5kjcygj47_hfyw9MZ 
https://drive.google.com/open?id=17he-FN8jpzz1GE9bQUQVAICFTLaY-ypn

**Comment by aukc1970** [comment]
Here is the address where you can check the menu:
http://pagecarton.ml
view-source:http://pagecarton.ml/
http://pagecarton.ml/test
view-source:http://pagecarton.ml/test

**Comment by ayoolafalola** [comment]
Kindly reinstall version 1.8.68. This issue should have been fixed now.

**Comment by aukc1970** [comment]
Thank you very much ! Everything works perfectly !

**Comment by ayoolafalola** [comment]
Awesome. Thanks for the great feedback.
